---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
    filename: gajar.txt
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
    become: yes
  - name: ensure apache is running (and enable it at boot)
    service:
      name: httpd
      state: started
      enabled: yes
    become: yes
  - name: create files and folders
    file:
      path: /opt/play
      state: directory
      mode: 0755
  - file:
      path: /opt/play/{{ filename }}
      state: touch
      mode: 0775
  - file:
      path: /opt/play2
      state: directory
      mode: 0777
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
